### ISSUE TITLE
No module named 'torchgeometry' 

### ISSUE THREAD

**Issue by Nivarrym** [carlosedubarreto/frankmocap_win_install#11]
Hi, after finishing installation I stuck at the execution step. At first I had the same error about the cv2 module, but managed to fix it with the help of google, but this.... Could you help me please? Explain what's wrong and what to do to fix it like I'm five years old. Thanks!
![image](https://user-images.githubusercontent.com/5613530/113512393-1b7bbc80-956d-11eb-8ed8-1610995a49b2.png)

**Comment by carlosedubarreto** [comment]
Hello.

I'll try to help you...

But I need that you execute that install bat and paste here the texte, so I can see where is the problem happening.


Its a long text, but dont worry copy it all here, please;

**Comment by Nivarrym** [comment]
Here it is, hope I did it right. Also, please don't close the issue if i'm away less than 24hrs (and if we wouldn't have solved it by that time), I suspect we might have a big time difference


> PS F:\Tools\frankmocap-master> .\install_win_full_body.bat /k
> 
> F:\Tools\frankmocap-master>rem ####### installing files pre packed
> 
> F:\Tools\frankmocap-master>REM pip install whl/faster_rcnn-0.1-cp37-cp37m-win_amd64.whl
> 
> F:\Tools\frankmocap-master>pip install whl/detectron2-0.3-cp37-cp37m-win_amd64.whl
> ERROR: detectron2-0.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
> 
> F:\Tools\frankmocap-master>pip install whl/opendr-0.73-py3-none-any.whl
> Processing f:\tools\frankmocap-master\whl\opendr-0.73-py3-none-any.whl
> Requirement already satisfied: chumpy>=0.58 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from opendr==0.73) (0.70)
> Requirement already satisfied: matplotlib in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from opendr==0.73) (3.4.1)
> Requirement already satisfied: Cython in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from opendr==0.73) (0.29.22)
> Requirement already satisfied: scipy>=0.13.0 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from chumpy>=0.58->opendr==0.73) (1.6.1)
> Requirement already satisfied: six>=1.11.0 in c:\users\branskugel\appdata\roaming\python\python38\site-packages (from chumpy>=0.58->opendr==0.73) (1.15.0)
> Requirement already satisfied: numpy>=1.16.5 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from scipy>=0.13.0->chumpy>=0.58->opendr==0.73) (1.20.1)
> Requirement already satisfied: python-dateutil>=2.7 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr==0.73) (2.8.1)
> Requirement already satisfied: pyparsing>=2.2.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr==0.73) (2.4.7)
> Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr==0.73) (1.3.1)
> Requirement already satisfied: cycler>=0.10 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr==0.73) (0.10.0)
> Requirement already satisfied: pillow>=6.2.0 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr==0.73) (8.2.0)
> opendr is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
> 
> F:\Tools\frankmocap-master>pip install whl/PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl
> ERROR: PyOpenGL-3.1.5-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
> 
> F:\Tools\frankmocap-master>pip install whl/PyOpenGL_accelerate-3.1.5-cp37-cp37m-win_amd64.whl
> ERROR: PyOpenGL_accelerate-3.1.5-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
> 
> F:\Tools\frankmocap-master>pip install -r requirements_alter.txt
> Requirement already satisfied: pip in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 1)) (21.0.1)
> Requirement already satisfied: gdown in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 2)) (3.12.2)
> Requirement already satisfied: requests in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 3)) (2.25.1)
> Requirement already satisfied: gitpython in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 4)) (3.1.14)
> Requirement already satisfied: opencv-python in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 5)) (4.5.1.48)
> Requirement already satisfied: pycocotools in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 6)) (2.0.2)
> Requirement already satisfied: pafy in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 7)) (0.5.5)
> Requirement already satisfied: youtube-dl in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 8)) (2021.4.1)
> Requirement already satisfied: scipy in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 9)) (1.6.1)
> Requirement already satisfied: pillow>=7.1.0 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 10)) (8.2.0)
> Requirement already satisfied: easydict in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 11)) (1.9)
> Requirement already satisfied: cython in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 12)) (0.29.22)
> Requirement already satisfied: cffi in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 13)) (1.14.5)
> Requirement already satisfied: msgpack in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 15)) (1.0.2)
> Requirement already satisfied: pyyaml in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 16)) (5.4.1)
> Requirement already satisfied: tensorboardX in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 17)) (2.2)
> Requirement already satisfied: tqdm in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 18)) (4.59.0)
> Requirement already satisfied: jinja2 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 19)) (2.11.3)
> Requirement already satisfied: smplx in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 20)) (0.1.26)
> Requirement already satisfied: sklearn in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 21)) (0.0)
> Requirement already satisfied: opendr in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 22)) (0.73)
> Requirement already satisfied: chumpy in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from -r requirements_alter.txt (line 23)) (0.70)
> Requirement already satisfied: pycparser in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from cffi->-r requirements_alter.txt (line 13)) (2.20)
> Requirement already satisfied: six>=1.11.0 in c:\users\branskugel\appdata\roaming\python\python38\site-packages (from chumpy->-r requirements_alter.txt (line 23)) (1.15.0)
> Requirement already satisfied: numpy>=1.16.5 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from scipy->-r requirements_alter.txt (line 9)) (1.20.1)
> Requirement already satisfied: filelock in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from gdown->-r requirements_alter.txt (line 2)) (3.0.12)
> Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from gitpython->-r requirements_alter.txt (line 4)) (4.0.7)
> Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->-r requirements_alter.txt (line 4)) (4.0.0)
> Requirement already satisfied: MarkupSafe>=0.23 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from jinja2->-r requirements_alter.txt (line 19)) (1.1.1)
> Requirement already satisfied: matplotlib in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from opendr->-r requirements_alter.txt (line 22)) (3.4.1)
> Requirement already satisfied: setuptools>=18.0 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from pycocotools->-r requirements_alter.txt (line 6)) (49.2.1)
> Requirement already satisfied: cycler>=0.10 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (0.10.0)
> Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (1.3.1)
> Requirement already satisfied: python-dateutil>=2.7 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (2.8.1)
> Requirement already satisfied: pyparsing>=2.2.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from matplotlib->opendr->-r requirements_alter.txt (line 22)) (2.4.7)
> Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (4.0.0)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (1.26.4)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (2020.12.5)
> Requirement already satisfied: idna<3,>=2.5 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (2.10)
> Requirement already satisfied: scikit-learn in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from sklearn->-r requirements_alter.txt (line 21)) (0.24.1)
> Requirement already satisfied: torchgeometry>=0.1.2 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from smplx->-r requirements_alter.txt (line 20)) (0.1.2)
> Requirement already satisfied: torch>=1.0.1.post2 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from smplx->-r requirements_alter.txt (line 20)) (1.8.1)
> Requirement already satisfied: typing-extensions in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from torch>=1.0.1.post2->smplx->-r requirements_alter.txt (line 20)) (3.7.4.3)
> Requirement already satisfied: protobuf>=3.8.0 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from tensorboardX->-r requirements_alter.txt (line 17)) (3.15.7)
> Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from requests->-r requirements_alter.txt (line 3)) (1.7.1)
> Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn->sklearn->-r requirements_alter.txt (line 21)) (2.1.0)
> Requirement already satisfied: joblib>=0.11 in c:\users\branskugel\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn->sklearn->-r requirements_alter.txt (line 21)) (1.0.1)
> 
> F:\Tools\frankmocap-master>echo Installing a third-party 2D keypoint detector
> Installing a third-party 2D keypoint detector
> 
> F:\Tools\frankmocap-master>python scripts_py/install_pose2d.py
> Creation of the directory F:\Tools\frankmocap-master/detectors failed
> Creation of the directory F:\Tools\frankmocap-master/extra_data/body_module/body_pose_estimator failed
> Downloading: checkpoint_iter_370000.pth
> 
> F:\Tools\frankmocap-master>echo Download extra data for body module
> Download extra data for body module
> 
> F:\Tools\frankmocap-master>python scripts_py/download_data_body_module.py
> Creation of the directory F:\Tools\frankmocap-master/extra_data/body_module failed
> Downloading: data.tar.gz
> Traceback (most recent call last):
>   File "scripts_py/download_data_body_module.py", line 32, in <module>
> FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data' -> 'data_from_spin'
> 
> F:\Tools\frankmocap-master>echo Installing a third-party hand detector
> Installing a third-party hand detector
> 
> F:\Tools\frankmocap-master>python scripts_py/install_hand_detectors.py
> Creation of the directory F:\Tools\frankmocap-master/extra_data/hand_module/hand_detector failed
> Downloading...
> From: https://drive.google.com/uc?id=1H2tWsZkS7tDF8q1-jdjx6V9XrK25EDbE
> To: F:\Tools\frankmocap-master\extra_data\hand_module\hand_detector\faster_rcnn_1_8_132028.pth
> 378MB [00:33, 11.1MB/s]
> Downloading...
> From: https://drive.google.com/uc?id=1OqgexNM52uxsPG3i8GuodDOJAGFsYkPg
> To: F:\Tools\frankmocap-master\extra_data\hand_module\hand_detector\model_0529999.pth
> 838MB [01:16, 11.0MB/s]
> 
> F:\Tools\frankmocap-master>rem installing the hand object detector
> 
> F:\Tools\frankmocap-master>REM "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
> 
> F:\Tools\frankmocap-master>set DISTUTILS_USE_SDK=1
> 
> F:\Tools\frankmocap-master>cd detectors\hand_object_detector\lib
> 
> F:\Tools\frankmocap-master\detectors\hand_object_detector\lib>python setup.py build develop
> No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0'
> running build
> running build_py
> running build_ext
> C:\Users\Branskugel\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> C:\Users\Branskugel\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>   warnings.warn(f'Error checking compiler version for {compiler}: {error}')
> building 'model._C' extension
> cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IF:\Tools\frankmocap-master\detectors\hand_object_detector\lib\model\csrc -IC:\Users\Branskugel\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\include -IC:\Users\Branskugel\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Branskugel\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\include\TH -IC:\Users\Branskugel\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\include\THC -IC:\Users\Branskugel\AppData\Local\Programs\Python\Python38\include -IC:\Users\Branskugel\AppData\Local\Programs\Python\Python38\include /EHsc /TpF:\Tools\frankmocap-master\detectors\hand_object_detector\lib\model\csrc\vision.cpp /Fobuild\temp.win-amd64-3.8\Release\Tools\frankmocap-master\detectors\hand_object_detector\lib\model\csrc\vision.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
> error: command 'cl.exe' failed: No such file or directory
> 
> F:\Tools\frankmocap-master\detectors\hand_object_detector\lib>cd ../../..
> 
> F:\Tools\frankmocap-master>echo Download extra data for hand module
> Download extra data for hand module
> 
> F:\Tools\frankmocap-master>python scripts_py/download_data_hand_module.py
> Creation of the directory F:\Tools\frankmocap-master/extra_data/hand_module failed
> Downloading: SMPLX_HAND_INFO.pkl
> Downloading: mean_mano_params.pkl
> Creation of the directory F:\Tools\frankmocap-master/extra_data/hand_module/pretrained_weights failed
> Downloading: pose_shape_best.pth
> 
> F:\Tools\frankmocap-master>echo Downloading sample videos
> Downloading sample videos
> 
> F:\Tools\frankmocap-master>python scripts_py/download_sample_video.py
> Downloading: sample_data_frank.tar
> PS F:\Tools\frankmocap-master>

**Comment by carlosedubarreto** [comment]
Looks like you are not on win 64....

The packages I pre packed are for win 64 only. sorry.

**Comment by Nivarrym** [comment]
> Looks like you are not on win 64....
> 
> The packages I pre packed are for win 64 only. sorry.

I am definitely on windows 64
![image](https://user-images.githubusercontent.com/5613530/113521091-066c5100-95a0-11eb-92da-b4e159292ab2.png)

**Comment by carlosedubarreto** [comment]
That's odd.

Well. 
I think the solution is to build those packages that you received error, like detectron and pyopengl.

**Comment by Nivarrym** [comment]
Could you tell me then how and what exactly should I do? So I don't get lost in google
Thanks

**Comment by carlosedubarreto** [comment]
That is the problem.

It was very difficult for me to do it.
I spent a lot of time to be able to build it myself. And I did it months ago.

What I would suggest you is trying to build, see the error and search for that error in any repository you find.

For example, when building detectron, if you have an issue, don't search only on the detectron repository, search wherever you find about that error, even on another repository that is not about detectron.

That was how I was able to build them myself.

I think that is the best I can tell to help you on that.

**Comment by Nivarrym** [comment]
I see... Well, wish me luck then! And thanks for your time and help.
One last question from me though. Will this possibly become a packed executable for installation as a full-fledged application one day? So that anyone else would not have to fight through difficult stuff and could have fun with motion capture straight away. Don't get me wrong, I very much appreciate your work here, it's just I'm a potato in such things.

**Comment by carlosedubarreto** [comment]
It depends on the creator of frankmocap.
I just tried to help people that use windows to install it.
And I still try to help giving orientation. But I don't have time available to support more complex matters like the one you are having.

**Comment by halfGuardian** [comment]
> I see... Well, wish me luck then! And thanks for your time and help.
> One last question from me though. Will this possibly become a packed executable for installation as a full-fledged application one day? So that anyone else would not have to fight through difficult stuff and could have fun with motion capture straight away. Don't get me wrong, I very much appreciate your work here, it's just I'm a potato in such things.

@Branskugel did you ever figure this out?  I'm having the same issue

**Comment by Nivarrym** [comment]
> > I see... Well, wish me luck then! And thanks for your time and help.
> > One last question from me though. Will this possibly become a packed executable for installation as a full-fledged application one day? So that anyone else would not have to fight through difficult stuff and could have fun with motion capture straight away. Don't get me wrong, I very much appreciate your work here, it's just I'm a potato in such things.
> 
> @Branskugel did you ever figure this out? I'm having the same issue

No, sorry, but I found this too difficult for my small brain to crack and gave it up untill later when it's easy and buttery smooth
😟

**Comment by halfGuardian** [comment]
@Branskugel I'm giving up too - I tried frankMocap and VIBE and got similar errors for both.  Maybe some amazing person will one day make a simple installer for us non-coding people :)

**Comment by Nivarrym** [comment]
> @Branskugel I'm giving up too - I tried frankMocap and VIBE and got similar errors for both. Maybe some amazing person will one day make a simple installer for us non-coding people :)

This person will be my hero. I'll make a legend about them and tell it to my kids, so they pass it further

**Comment by carlosedubarreto** [comment]
@Branskugel and @halfGuardian , I know it is not the best solution, but one that could work for you both.

using google Colab.

This way you could use the google computaers to make the work for you, and probably wont have those issues.

here is an answer from frankmocap github explaining how to do.

https://github.com/facebookresearch/frankmocap/issues/28

**Comment by Vodav** [comment]
The command
pip install torchgeometry
worked for me, hopefully it helps you, Im still stuck with other modules though XD

**Comment by AhmedShalabe** [comment]
> The command
> pip install torchgeometry
> worked for me, hopefully it helps you, Im still stuck with other modules though XD

Thanks, man. This worked also for me 
But  I got a msg Current version only supports GPU because I don't have Nvidia card

**Comment by carlosedubarreto** [comment]
Thats sad....
Maybe you could try using google colab. maybe it work well with you @AhmedShalabe . Use googles GPU to do the work that you need.

**Comment by Mario-LuX** [comment]
I met with the same problem, finally I solved that. Actually I think that's all due to the difference between the Linux and Windows.
First, the reason that torchgeometry doesn't exist is that it doesn't exist in the default conda resource channel, so use pip install torchgeometry

And after that, you will meet plenty of issues indicating that the code cannot find this module, cannot find that file, blabla...
This is because the authors of this project wrote the code in accordance with the requirements of the Linux system, so when they import other modules or load files from another directory, the path format does not conform to Windows system. So you need to modify the import code and many file format in the corresponding file every time there's an error. Then you can see the right results.

**Comment by carlosedubarreto** [comment]
Nice explanation @Mario-LuX  Thanks!!!

**Comment by Biotry** [comment]
> I met with the same problem, finally I solved that. Actually I think that's all due to the difference between the Linux and Windows.
> First, the reason that torchgeometry doesn't exist is that it doesn't exist in the default conda resource channel, so use pip install torchgeometry
> 
> And after that, you will meet plenty of issues indicating that the code cannot find this module, cannot find that file, blabla...
> This is because the authors of this project wrote the code in accordance with the requirements of the Linux system, so when they import other modules or load files from another directory, the path format does not conform to Windows system. So you need to modify the import code and many file format in the corresponding file every time there's an error. Then you can see the right results.

Hey @Mario-LuX  and @carlosedubarreto ! I'm trying to solve the issues that you have mentionned in this chat, did you have this one ?

File "D:\anaconda3\envs\frankmocap\lib\site-packages\detectron2\layers\deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: DLL load failed: Le module spécifié est introuvable.

I've checked the _C  code, and there is nothing in it that's why it's not working.

![image](https://user-images.githubusercontent.com/61778297/126904424-d5b2c18a-a0d5-468d-a2fd-29a2cd0d894d.png)

I don't know what I should change to solve this, I think there is a problem with the format of _C code, it's in .pyd and all the other codes are in .py

Hope I've been clear, by the way is there any hope that cuda works on a AMD Ryzen 5 ?
Thanks!!

**Comment by Mario-LuX** [comment]
@Biotry I don't have this one, sorry.
And I notice that this error located in D:\anaconda3\envs\frankmocap\lib\site-packages\detectron2 but not within Frankmocap repository, So I think this error is not caused by a flaw in the Frankmocap code. I tend to believe something is wrong with the detectron2 you installed. In addition, you mentioned that you are using an AMD graphics card. CUDA seems to only support Nvidia graphics cards. Maybe you can google and refer to other tutorials to see how you can configure AMD graphics cards to support cuda, because detectron2 is a framework developed based on Pytorch. Maybe this error is related to the fact that you don't have cuda support.

**Comment by carlosedubarreto** [comment]
There is also another "problem" I pre compiled the detectron to make it easier to people to install frankmocap, if i remember correclty, so it was based on my pc configuration, wich is also using Nvidia Card...

So I think you would also have to compile Detectron 2 by yourself to make it work (if it is possible to be compiled using AMD cards, and that I dont know)

You will have better chances of sucess checking/opening an issue here
https://github.com/facebookresearch/frankmocap/issues

and/or here
https://github.com/facebookresearch/detectron2/issues

**Comment by kingaladdin** [comment]
> Hi, after finishing installation I stuck at the execution step. At first I had the same error about the cv2 module, but managed to fix it with the help of google, but this.... Could you help me please? Explain what's wrong and what to do to fix it like I'm five years old. Thanks! ![image](https://user-images.githubusercontent.com/5613530/113512393-1b7bbc80-956d-11eb-8ed8-1610995a49b2.png)

How did you resolve the cv2 module missing?

**Comment by carlosedubarreto** [comment]
> 
> How did you resolve the cv2 module missing?

with
`pip install opencv-python`

**Comment by kingaladdin** [comment]
> 

Dang you quick lol. I still have anaconda up and running. Thanks for the help!
