### ISSUE TITLE
Current version only supports GPU

### ISSUE THREAD

**Issue by jamalknight** [carlosedubarreto/frankmocap_win_install#20]
I have Nvidia GPU but get this error. Any ideas why?

Command:
`python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl`

error:
```
(frankmocap) C:\MOCAP\frankmocap>python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl
Traceback (most recent call last):
  File "C:\Users\jamal\anaconda3\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jamal\anaconda3\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap.py", line 247, in <module>
    main()
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap.py", line 228, in main
    assert torch.cuda.is_available(), "Current version only supports GPU"
AssertionError: Current version only supports GPU
```

**Comment by carlosedubarreto** [comment]
sorry I didnt see the notification for this question.
But I guess your problem is the cuda version.
Probably yout card is very new, like a RTX 3070
