### ISSUE TITLE
Issue when running the execution test

### ISSUE THREAD

**Issue by Endeling** [carlosedubarreto/frankmocap_win_install#23]
When i try the execution test this error shows up:
(frankmocap) C:\MOCAP\frankmocap>python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl
Traceback (most recent call last):
  File "C:\Users\Emanuele\miniconda3\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Emanuele\miniconda3\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap.py", line 247, in <module>
    main()
  File "C:\MOCAP\frankmocap\demo\demo_frankmocap.py", line 228, in main
    assert torch.cuda.is_available(), "Current version only supports GPU"
AssertionError: Current version only supports GPU

**Comment by carlosedubarreto** [comment]
Please run the installation bat again and send here what shows on your screen.

So I can see what problem raised during the installation.
