### ISSUE TITLE
Error running frankmocap

### ISSUE THREAD

**Issue by CGMikeG** [carlosedubarreto/frankmocap_win_install#34]
Hi, you wouldn't happen to know how to fix below errors. Thanks.

(frankmocap) M:\GITHUB\FRANKMOCAP>python -m demo.demo_frankmocap --input_path ./sampledata/single_totalbody.mp4 --out_dir ./mocap_output --save_pred_pkl

Traceback (most recent call last):
  File "C:\Users\Venice\.conda\envs\frankmocap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Venice\.conda\envs\frankmocap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "M:\GITHUB\FRANKMOCAP\demo\demo_frankmocap.py", line 16, in <module>
    from bodymocap.body_mocap_api import BodyMocap
  File "M:\GITHUB\FRANKMOCAP\bodymocap\body_mocap_api.py", line 10, in <module>
    from bodymocap.models import hmr, SMPL, SMPLX
  File "M:\GITHUB\FRANKMOCAP\bodymocap\models\__init__.py", line 1, in <module>
    from .hmr import hmr
  File "M:\GITHUB\FRANKMOCAP\bodymocap\models\hmr.py", line 10, in <module>
    from bodymocap.utils.geometry import rot6d_to_rotmat
  File "M:\GITHUB\FRANKMOCAP\bodymocap\utils\geometry.py", line 8, in <module>
    import torchgeometry
ModuleNotFoundError: No module named 'torchgeometry'

**Comment by carlosedubarreto** [comment]
try this

https://github.com/carlosedubarreto/frankmocap_win_install/issues/11#issuecomment-846609519

**Comment by CGMikeG** [comment]
lol. Newbie mistake. I did thought of using this command but for some reason, I thought pip won't work on miniconda. I should have just tried anyway, it would have saved so much headache. Anyway for anybody who would see these comments first the command is pip install torchgeometry

**Comment by carlosedubarreto** [comment]
Thanks for the feedback.
I'm going to close this issue.
